### ISSUE TITLE
CompleteForm:

### ISSUE THREAD

**Issue by cdesch** [ittybittydude/IBAForms#15]
When completing the form, the field that was last edited (has the current edit in it (cursor, if you will)) isn't saved to the dictionary as it has not finished editing. How can do you resign the firstresponder for this field such that the setModelValue will save the value to the dictionary so it can be processed in the completeForm?

``` ruby
- (void)completeEditForm:(id)sender{


    //Validate

    if ([self.itemModel valueForKey:@"number"] == nil || [[self.itemModel valueForKey:@"number"] isEqualToString:@""]) {
       //DO SOMETHING
     }
}
```

**Comment by sadatrahman** [comment]
You can resign the first responder by calling:

``` objective-c
[[IBAInputManager sharedIBAInputManager] setActiveInputRequestor:nil];
```
