### ISSUE TITLE
TextForm field issue with empty value

### ISSUE THREAD

**Issue by krzyzanowskim** [ittybittydude/IBAForms#19]
Hi,

I have noticed that if I have at least 2 text fields in one section, and start filing data in order so first one is filled, then second one is filled and then I tap at custom button on view that process values, then the second text field is empty (nil). "textFieldShouldReturn", nor "deactivate" is not called at all. I'm not sure why. (iOS 5.0.1)

**Comment by sadatrahman** [comment]
You should call `[[IBAInputManager sharedIBAInputManager] deactivateActiveInputRequestor];` within your custom button action block in order to get the last field to commit it's value to the model.

**Comment by krzyzanowskim** [comment]
thanks that's indeed the solution. Good to have it somewehere in docs for IBAForms beginners like me.

**Comment by sadatrahman** [comment]
Thanks for your feedback, Marcin. We are working towards setting up a blog for IBAForms to cover some of these common gotchas that come up from time to time for new users.
