### ISSUE TITLE
Slider FormField

### ISSUE THREAD

**Issue by alohasoftworks** [ittybittydude/IBAForms#21]
Hi there,

Great work on this product, it makes my life a lot easier.

On a recent project, I found need for a slider form field but noticed that this widget is absent from IBAForms. I wrote a custom class based partially on the boolean form field. I'd like to contribute it upstream.

**Comment by ittybittydude** [comment]
Hey James, fork the codebase and submit a pull request when you have something we can look at. Remember to add your slider field to the showcase so we can see how it works.
