### ISSUE TITLE
IBATextFormField with default value?

### ISSUE THREAD

**Issue by uzman** [ittybittydude/IBAForms#23]
hi, I'm the beginner for IBAForms.

is it possible to create a IBATextFormField with default value?

**Comment by uzman** [comment]
ok i found it, but it doesn't display the text.

IBATextFormField *name1 = [[IBATextFormField alloc] initWithKeyPath:@"name" title:@"Name"];
[section1 addFormField:[name1 autorelease]];
name1.textFormFieldCell.textField.text=@"Default Name";// it doesn't show the Text.
name1.textFormFieldCell.textField.placeholder=@"placeholder";// it is OK

any help?

**Comment by sadatrahman** [comment]
Not an issue.
Please ask for help within the dedicated Google Groups forum for IBAForms:
https://groups.google.com/forum/#!forum/ibaforms
