### ISSUE TITLE
I'm stuck, can't see the whole form

### ISSUE THREAD

**Issue by fulldecent** [ittybittydude/IBAForms#29]
![Screen Shot 2013-01-20 at 1 06 49 AM](https://f.cloud.github.com/assets/382183/80892/a08d94de-62c7-11e2-804e-13b77a51d424.png)

**Comment by ittybittydude** [comment]
Erm, try scrolling the form up...

Actually, I see now that it looks like the keyboard area is raised slightly, which is weird. Not sure how it got in to that state. 

Can you reproduce?

**Comment by fulldecent** [comment]
Every time. 
   Run Showcase
   Select all ON and Form Sheet, Show Sample Form
   Click multiple pick list
Page is stuck, can't get to rest of form
